### ISSUE TITLE
The Menu component and useLayoutEffect is not optimal with SSR

### ISSUE THREAD

**Issue by wenche** [equinor/design-system#2630]
Disclaimer: Yes, I know that EDS is not made with SSR as a first class citizen, _however_

When we use the Menu component in our Next.js app, we get a lot of warnings in the server side logs because of the useLayoutEffect hook. Is it possible to rethink this for better support with server side rendering? 

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at Menu (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/@equinor/eds-core-react/dist/eds-core-react.cjs.js:8292:5)
    at nav
    at div
    at I (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/styled-components/dist/styled-components.cjs.js:1:19189)
    at Actions (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/@equinor/eds-core-react/dist/eds-core-react.cjs.js:4414:5)
    at header
    at I (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/styled-components/dist/styled-components.cjs.js:1:19189)
    at Paper (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/@equinor/eds-core-react/dist/eds-core-react.cjs.js:4106:16)
    at I (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/styled-components/dist/styled-components.cjs.js:1:19189)
    at exports.ThemeProvider (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/styled-components/dist/styled-components.cjs.js:1:24886)
    at TopBar (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/@equinor/eds-core-react/dist/eds-core-react.cjs.js:4382:5)
    at I (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/styled-components/dist/styled-components.cjs.js:1:19189)
    at div
    at I (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/styled-components/dist/styled-components.cjs.js:1:19189)
    at NavBar (webpack-internal:///./components/NavBar/NavBar.tsx:63:100)
    at div
    at I (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/styled-components/dist/styled-components.cjs.js:1:19189)
    at Page (webpack-internal:///./components/Page/Page.tsx:32:17)
    at SignIn (webpack-internal:///./pages/auth/signin.tsx:59:69)
    at AppInsightsErrorBoundary (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/@microsoft/applicationinsights-react-js/dist/applicationinsights-react-js.js:2212:51)
    at IntlProvider (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/react-intl/src/components/provider.js:88:47)
    at SessionProvider (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/next-auth/react/index.js:445:24)
    at App (webpack-internal:///./pages/_app.tsx:28:16)
    at ae (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/styled-components/dist/styled-components.cjs.js:1:13265)
    at StyleRegistry (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/styled-jsx/dist/index/index.js:448:36)
    at AppContainer (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/next/dist/server/render.js:298:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/next/dist/server/render.js:327:57)
    at div
    at Body (/Users/wenche/Documents/prosjekter/equinor-data-marketplace/data-marketplace/node_modules/next/dist/server/render.js:614:21)
```

We will try to lazy load the component in our application as per now, like described in https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85, but it would be nice if this could have been taken into consideration in EDS itself :thumbsup:

**Comment by wenche** [comment]
Yes, something like that might be an idea if the layout effect is a crucial part client side :)

**Comment by wenche** [comment]
FYI: [This is our workaround atm](https://github.com/equinor/data-marketplace/pull/277/commits/3b5605a0d72d1a66e01892a27657349ea7f759f5)
